import {useEffect,useRef} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {decodeModelResponse} from './model-download';
import {PointerTap} from './pointer-tap';
import {SYSTEMS,type Atlas,type SceneState} from './anatomy';

type ClinicalMode='actual'|'target'|null;
interface Props{atlas:Atlas;state:SceneState;onSelect:(id:string)=>void;onProgress:(n:number)=>void;onError:(s:string)=>void;clinicalMode?:ClinicalMode;clinicalFocus?:boolean}
type ShaderRef={uniforms:Record<string,{value:any}>};

export default function HologramSceneV3({atlas,state,onSelect,onProgress,onError,clinicalMode=null,clinicalFocus=false}:Props){
 const host=useRef<HTMLDivElement>(null),latest=useRef(state),select=useRef(onSelect),modeRef=useRef<ClinicalMode>(clinicalMode),focusRef=useRef(clinicalFocus);
 latest.current=state;select.current=onSelect;modeRef.current=clinicalMode;focusRef.current=clinicalFocus;
 useEffect(()=>{
  const el=host.current!;let disposed=false,frame=0,ready=false,lastKey='',lastView='',lastReset=-1;
  const abort=new AbortController();
  let renderer:T.WebGLRenderer;
  try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{onError('No se pudo iniciar el visor 3D.');return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,el.clientWidth<768?1.25:1.6));renderer.setClearColor('#020814');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.82;el.appendChild(renderer.domElement);
  renderer.domElement.setAttribute('aria-label','Gemelo biológico VLI holográfico interactivo');
  const scene=new T.Scene();scene.fog=new T.FogExp2(0x020814,.035);
  const camera=new T.PerspectiveCamera(32,1,.01,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=.55;controls.maxDistance=8;controls.maxPolarAngle=Math.PI*.96;
  const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.02);scene.environment=env.texture;room.dispose();pmrem.dispose();
  scene.add(new T.HemisphereLight(0x5ddcff,0x02030a,.7));
  const key=new T.DirectionalLight(0xa8efff,1.2);key.position.set(-2,3,2);scene.add(key);
  const rim=new T.DirectionalLight(0x00bfff,1.5);rim.position.set(2,2,-2);scene.add(rim);
  const organLight=new T.PointLight(0xff9138,1.6,2.2);organLight.position.set(.15,1.08,1.15);scene.add(organLight);

  const rings:T.Mesh[]=[];[.62,.77,.92].forEach((r,i)=>{const m=new T.Mesh(new T.RingGeometry(r,r+.006,128),new T.MeshBasicMaterial({color:i===0?0x5ce7ff:0x159cc7,transparent:true,opacity:i===0?.48:.18,side:T.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=-.005+i*.001;scene.add(m);rings.push(m);});
  const scanRing=new T.Mesh(new T.TorusGeometry(.56,.004,8,128),new T.MeshBasicMaterial({color:0x67e8f9,transparent:true,opacity:.26,depthWrite:false}));scanRing.rotation.x=Math.PI/2;scene.add(scanRing);
  const pCount=120,pPos=new Float32Array(pCount*3);for(let i=0;i<pCount;i++){const a=Math.random()*Math.PI*2,r=.85+Math.random()*.75;pPos[i*3]=Math.cos(a)*r;pPos[i*3+1]=Math.random()*2.05;pPos[i*3+2]=Math.sin(a)*r*.38;}const pGeo=new T.BufferGeometry();pGeo.setAttribute('position',new T.BufferAttribute(pPos,3));const pMat=new T.PointsMaterial({color:0x45d7ff,size:.006,transparent:true,opacity:.16,depthWrite:false});const particles=new T.Points(pGeo,pMat);scene.add(particles);

  const width=T.MathUtils.ceilPowerOfTwo(atlas.parts.length),partData=new Float32Array(width*4),partTexture=new T.DataTexture(partData,width,1,T.RGBAFormat,T.FloatType);partTexture.needsUpdate=true;const selData=new Uint8Array(width*4),selTexture=new T.DataTexture(selData,width,1);selTexture.needsUpdate=true;
  const pickers:(T.Mesh|undefined)[]=[],geometries:T.BufferGeometry[]=[],materials:T.Material[]=[],shaderRefs:ShaderRef[]=[],shellRefs:ShaderRef[]=[];
  const bounds=atlas.parts.map(p=>new T.Box3(new T.Vector3().fromArray(p.bounds[0]),new T.Vector3().fromArray(p.bounds[1])));

  const baseOpacity=(system:string)=>system==='integumentary'?.055:system==='skeletal'?.09:system==='muscular'?.12:.18;
  const makeBase=(system:string)=>{const sys=SYSTEMS.find(s=>s.id===system),op=baseOpacity(system);const m=new T.MeshStandardMaterial({color:sys?.color??'#6bb9c7',metalness:.02,roughness:.46,transparent:true,opacity:1,side:T.DoubleSide,depthWrite:false,emissive:new T.Color(sys?.color??'#1e5260'),emissiveIntensity:.06});m.onBeforeCompile=shader=>{shader.uniforms.partState={value:partTexture};shader.uniforms.selectionState={value:selTexture};shader.uniforms.stateWidth={value:width};shader.uniforms.selectedColor={value:new T.Color('#ff9138')};shader.uniforms.focus={value:0};shader.uniforms.pulse={value:0};shader.uniforms.baseOpacity={value:op};shader.vertexShader='attribute float partIndex; uniform sampler2D partState; uniform sampler2D selectionState; uniform float stateWidth; varying float vVisible; varying float vSelected;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvec2 uvState=vec2((partIndex+0.5)/stateWidth,0.5);vec4 st=texture2D(partState,uvState);transformed+=st.xyz;vVisible=st.w;vSelected=texture2D(selectionState,uvState).r;');shader.fragmentShader='uniform vec3 selectedColor;uniform float focus;uniform float pulse;uniform float baseOpacity;varying float vVisible;varying float vSelected;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nif(vVisible<0.5)discard;');shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat nonSelAlpha=mix(baseOpacity,baseOpacity*.55,focus);diffuseColor.a=mix(nonSelAlpha,.96,vSelected);diffuseColor.rgb=mix(diffuseColor.rgb,selectedColor,vSelected*.96);diffuseColor.rgb*=mix(1.0,1.05+.08*pulse,vSelected);');shaderRefs.push(shader as ShaderRef);};materials.push(m);return m;};
  const makeShell=(system:string)=>{const op=system==='integumentary'?.08:.035;const m=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{partState:{value:partTexture},selectionState:{value:selTexture},stateWidth:{value:width},selectedColor:{value:new T.Color('#ff9138')},focus:{value:0},time:{value:0},shellOpacity:{value:op}},vertexShader:`attribute float partIndex;uniform sampler2D partState;uniform sampler2D selectionState;uniform float stateWidth;varying float vVisible;varying float vSelected;varying vec3 vWorld;varying vec3 vNormal;void main(){vec2 u=vec2((partIndex+0.5)/stateWidth,0.5);vec4 st=texture2D(partState,u);vec3 p=position+st.xyz;vVisible=st.w;vSelected=texture2D(selectionState,u).r;vec4 wp=modelMatrix*vec4(p,1.0);vWorld=wp.xyz;vNormal=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*wp;}`,fragmentShader:`uniform vec3 selectedColor;uniform float focus;uniform float time;uniform float shellOpacity;varying float vVisible;varying float vSelected;varying vec3 vWorld;varying vec3 vNormal;void main(){if(vVisible<0.5)discard;vec3 V=normalize(cameraPosition-vWorld);float fres=pow(1.0-abs(dot(normalize(vNormal),V)),2.8);float scan=smoothstep(.92,1.0,sin(vWorld.y*150.0-time*3.2)*.5+.5);vec3 c=mix(vec3(.08,.60,.86),selectedColor,vSelected);float a=shellOpacity+fres*.12+scan*.018;a=mix(a,.28+fres*.22,vSelected);if(focus>0.5&&vSelected<.5)a*=.55;gl_FragColor=vec4(c,a);}`});materials.push(m);shellRefs.push(m as unknown as ShaderRef);return m;};
  const baseMats=new Map(SYSTEMS.map(s=>[s.id,makeBase(s.id)])),shellMats=new Map(SYSTEMS.map(s=>[s.id,makeShell(s.id)]));
  let loaded=0;const loadChunk=async(ci:number)=>{const chunk=atlas.chunks[ci],compressed=!!chunk.gzip&&typeof DecompressionStream!=='undefined';const response=await fetch(compressed?chunk.gzip!:chunk.url,{signal:abort.signal});const buffer=await decodeModelResponse(response,chunk.bytes,compressed);if(disposed)return;const groups=new Map<string,T.BufferGeometry[]>();atlas.parts.forEach((p,i)=>{if(p.chunk!==ci)return;const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(new Float32Array(buffer,p.positions,p.vertexCount*3),3));g.setAttribute('normal',new T.BufferAttribute(new Int16Array(buffer,p.normals,p.vertexCount*3),3,true));g.setIndex(new T.BufferAttribute(new Uint32Array(buffer,p.indices,p.indexCount),1));g.boundingBox=bounds[i].clone();g.computeBoundingSphere();g.setAttribute('partIndex',new T.BufferAttribute(new Float32Array(p.vertexCount).fill(i),1));const pick=new T.Mesh(g);pick.matrixAutoUpdate=false;pickers[i]=pick;geometries.push(g);const list=groups.get(p.system)??[];list.push(g);groups.set(p.system,list);});groups.forEach((gs,system)=>{const merged=mergeGeometries(gs,false);if(!merged)return;geometries.push(merged);const base=new T.Mesh(merged,baseMats.get(system as never));base.frustumCulled=false;scene.add(base);const shell=new T.Mesh(merged,shellMats.get(system as never));shell.frustumCulled=false;shell.renderOrder=3;scene.add(shell);});loaded++;onProgress(Math.round(loaded/atlas.chunks.length*100));};

  const fitBody=()=>{camera.clearViewOffset();const v=latest.current.view;const dir=v==='back'?new T.Vector3(0,.03,-1):v==='side'?new T.Vector3(1,.03,0):v==='three-quarter'?new T.Vector3(.34,.05,1).normalize():new T.Vector3(0,.03,1);controls.target.set(0,.88,0);camera.position.copy(controls.target).addScaledVector(dir,3.25);controls.update();};
  const fitSelection=()=>{const ids=new Set(latest.current.selected),box=new T.Box3();atlas.parts.forEach((p,i)=>{if(ids.has(p.id))box.union(bounds[i].clone().translate(pickers[i]?.position??new T.Vector3()));});if(box.isEmpty())return;const c=box.getCenter(new T.Vector3()),s=box.getSize(new T.Vector3()),r=Math.max(s.x,s.y,s.z,.15);controls.target.copy(c);camera.position.copy(c).add(new T.Vector3(.22,.12,1).normalize().multiplyScalar(Math.max(.72,r*4.1)));controls.update();};
  const updateState=()=>{const s=latest.current,visible=new Set(s.visible),selected=new Set(s.selected),focus=focusRef.current;atlas.parts.forEach((p,i)=>{const sel=selected.has(p.id),show=s.isolate?sel:visible.has(p.system)||sel,push=focus&&sel&&!s.isolate?.10:0;partData.set([0,0,push,show?1:0],i*4);selData[i*4]=sel?255:0;const pick=pickers[i];if(pick){pick.position.set(0,0,push);pick.updateMatrix();pick.updateMatrixWorld(true);}});partTexture.needsUpdate=true;selTexture.needsUpdate=true;};
  (async()=>{try{let cursor=0;await Promise.all(Array.from({length:3},async()=>{while(cursor<atlas.chunks.length){const i=cursor++;await loadChunk(i);}}));if(!disposed){ready=true;updateState();fitBody();}}catch(e){if(!disposed)onError(e instanceof Error?e.message:'No se pudo cargar la anatomía VLI.');}})();

  const raycaster=new T.Raycaster(),pointer=new T.Vector2(),tap=new PointerTap(),worldBox=new T.Box3(),hitPoint=new T.Vector3();const down=(e:PointerEvent)=>tap.down(e.pointerId,e.clientX,e.clientY,e.pointerType==='touch'?12:5),move=(e:PointerEvent)=>tap.move(e.pointerId,e.clientX,e.clientY),cancel=(e:PointerEvent)=>tap.cancel(e.pointerId),up=(e:PointerEvent)=>{if(!tap.up(e.pointerId,e.clientX,e.clientY)||!ready)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);let nearest=Infinity,found=-1;pickers.forEach((mesh,i)=>{if(!mesh||partData[i*4+3]<.5)return;worldBox.copy(bounds[i]).translate(mesh.position);if(!raycaster.ray.intersectBox(worldBox,hitPoint))return;const hits=raycaster.intersectObject(mesh,false);if(hits[0]&&hits[0].distance<nearest){nearest=hits[0].distance;found=i;}});if(found>=0)select.current(atlas.parts[found].id);};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',cancel);

  const resize=()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,el.clientWidth<768?1.25:1.6));camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);};const ro=new ResizeObserver(resize);ro.observe(el);resize();
  const clock=new T.Clock();const animate=()=>{if(disposed)return;frame=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),time=clock.elapsedTime,s=latest.current,mode=modeRef.current,pulse=(Math.sin(time*3.1)+1)/2,key=[s.selected.join(','),s.isolate,focusRef.current].join('|');if(key!==lastKey){updateState();s.isolate?fitSelection():fitBody();lastKey=key;}if(s.view!==lastView||s.reset!==lastReset){s.isolate?fitSelection():fitBody();lastView=s.view;lastReset=s.reset;}const selColor=mode==='target'?'#36e8a2':'#ff9138';shaderRefs.forEach(r=>{r.uniforms.focus.value=focusRef.current?1:0;r.uniforms.pulse.value=pulse;r.uniforms.selectedColor.value.set(selColor);});shellRefs.forEach(r=>{r.uniforms.focus.value=focusRef.current?1:0;r.uniforms.time.value=time;r.uniforms.selectedColor.value.set(selColor);});organLight.color.set(selColor);organLight.intensity=focusRef.current?1.35+.35*pulse:.4;rings.forEach((r,i)=>r.rotation.z+=(i%2?-1:1)*dt*.05);scanRing.position.y=.04+((time*.16)%1.8);particles.rotation.y+=dt*.006;controls.autoRotate=!!s.rotate;controls.autoRotateSpeed=s.isolate?1.1:.35;controls.update();renderer.render(scene,camera);};animate();
  return()=>{disposed=true;abort.abort();cancelAnimationFrame(frame);ro.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',cancel);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());pGeo.dispose();pMat.dispose();partTexture.dispose();selTexture.dispose();env.dispose();renderer.dispose();renderer.domElement.remove();};
 },[atlas]);
 return <div className="scene" ref={host}/>;
}
